# Generated by Django 4.2.7 on 2023-12-06 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("MainApp", "0003_userdetails"),
    ]

    operations = [
        migrations.RemoveField(model_name="userdetails", name="rating",),
        migrations.AddField(
            model_name="userdetails",
            name="profile_picture",
            field=models.ImageField(
                blank=True, null=True, upload_to="static/profile_pictures/"
            ),
        ),
    ]
