# Generated by Django 4.2.7 on 2023-12-06 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("MainApp", "0004_remove_userdetails_rating_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userdetails",
            name="profile_picture",
            field=models.ImageField(
                blank=True, null=True, upload_to="profile_pictures/"
            ),
        ),
        migrations.AlterField(
            model_name="userdetails",
            name="resume",
            field=models.FileField(blank=True, null=True, upload_to="resumes/"),
        ),
    ]
