# Generated by Django 4.2.7 on 2023-12-12 18:35

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("MainApp", "0009_alter_project_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="post_image",
            field=models.ImageField(blank=True, null=True, upload_to="post/images/"),
        ),
        migrations.AlterField(
            model_name="post", name="content", field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name="post",
            name="like",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name="post",
            name="title",
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
