# Generated by Django 4.2.7 on 2023-12-07 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0005_alter_userdetails_profile_picture_and_more'),
        ('MainApp', '0007_rename_tagged_pots_post_tags_alter_post_content_and_more'),
    ]

    operations = [
    ]
